exclude: "^.*(migrations).*$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.22.1
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    # flake8 config is in setup.cfg
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.6"  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        args: [-t, "2"]
