[tool.poetry]
name = "cast_registry"
version = "0.1.0"
description = "Just to be able to register domains/podcasts.."
authors = ["Jochen Wersdörfer"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.1"
django-htmx = "^1.6.0"
django-allauth = "^0.50"
django-environ = "^0.8.1"
httpx = "^0.22.0"
pydantic = "^1.9.0"
psycopg2 = "^2.9.3"
gunicorn = "^20.1.0"
whitenoise = "^6.2.0"
django-anymail = {extras = ["mailgun"], version = "*"}

[tool.poetry.dev-dependencies]
black = "^21.12b0"
jupyterlab = "^3.2.6"
django-extensions = "^3.1.5"
django-debug-toolbar = "^3.2.4"
pyproject-flake8 = "^0.0.1-alpha.2"
Faker = "^11.3.0"
honcho = "^1.1.0"
djhtml = "^1.4.11"
nb-black = "^1.0.7"
pytest = "^7.1.2"
pytest-django = "^4.5.2"
coverage = "^6.4.1"
mypy = "^0.961"
django-stubs = {extras = ["compatible-mypy"], version = "^1.12.0"}
notebook = "^6.4.12"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"

[tool.flake8]
statistics = "True"
ignore = ["D203" , "W503"]
max-line-length = 119
exclude = '''
    .git,
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango41Warning",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
source = ["apps"]
omit = ["apps/registry/tests/*", "apps/registry/migrations"]
command_line = "-m pytest"

[tool.mypy]
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings.development"
