[tool.poetry]
name = "cast_registry"
version = "0.1.0"
description = "Just to be able to register domains/podcasts.."
authors = ["Jochen Wersdörfer"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.1"
django-htmx = "^1.6.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[tool.black]
line-length = 119

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
