[tool.poetry]
name = "cast_registry"
version = "0.1.0"
description = "Just to be able to register domains/podcasts.."
authors = ["Jochen Wersdörfer"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.1"
django-htmx = "^1.6.0"
django-allauth = "^0.50"
django-environ = "^0.8.1"
httpx = "^0.22.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
jupyterlab = "^3.2.6"
django-extensions = "^3.1.5"
django-debug-toolbar = "^3.2.4"
pyproject-flake8 = "^0.0.1-alpha.2"
Faker = "^11.3.0"
honcho = "^1.1.0"
djhtml = "^1.4.11"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"

[tool.flake8]
statistics = "True"
ignore = ["D203" , "W503"]
max-line-length = 119
exclude = '''
    .git,
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
