# Generated by Django 4.0.5 on 2022-07-10 13:32

import apps.registry.serializers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_domain_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='fqdn',
            field=models.CharField(max_length=255, unique=True, verbose_name='Enter Fully Qualified Domain Name'),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(encoder=apps.registry.serializers.RegistryJSONEncoder, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.domain')),
            ],
        ),
    ]
