# Generated by Django 4.0.5 on 2022-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_create_deployment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='target',
            field=models.CharField(choices=[('DP', 'Deploy'), ('RM', 'Remove')], default='DP', max_length=2),
        ),
    ]
