# Generated by Django 4.0.6 on 2022-07-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_add_deployment_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='backend',
            field=models.CharField(choices=[('CA', 'Django-Cast'), ('WP', 'Wordpress')], default='CA', max_length=2),
        ),
    ]
