# Generated by Django 4.1 on 2022-08-04 04:46

import apps.registry.serializers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0004_add_domain_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="processed_steps",
            field=models.JSONField(default=[], encoder=apps.registry.serializers.RegistryJSONEncoder),
        ),
    ]
