# Generated by Django 5.1.2 on 2024-10-17 11:11

import apps.registry.serializers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_save_processed_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='data',
            field=models.JSONField(default=dict, encoder=apps.registry.serializers.RegistryJSONEncoder, null=True),
        ),
    ]
