# Generated by Django 5.1.2 on 2024-10-17 11:12

import apps.registry.serializers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_deployment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='processed_steps',
            field=models.JSONField(default=list, encoder=apps.registry.serializers.RegistryJSONEncoder),
        ),
    ]
