---
# variables for registry
username: registry
home_path: "/home/{{ username }}"
deploy_home: /home/deploy
site_path: "{{ home_path }}/site"
services_path: "/home/deploy/site/services"
global_python: python3.10
ansible_venv_bin: "{{ deploy_home }}/ansible_venv/bin"
ansible_python: "{{ ansible_venv_bin }}/python"
default_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
fqdn: "registry.staging.django-cast.com"
port: 10000
django_settings_module: "config.settings.production"
traefik_config_path: "/etc/traefik/dynamic/{{ username }}.traefik.yml"
systemd_unit_path: "/etc/systemd/system/{{ username }}.service"
deploy_base_url: "https://deploy.staging.wersdoerfer.de"
mailgun_domain: "mg.registry.staging.django-cast.com"
