---
# variables for registry
username: registry
home_path: "/home/{{ username }}"
deploy_home: /home/deploy
site_path: "{{ home_path }}/site"
services_path: "/home/deploy/site/services"
global_python: python3.13
uv_path: "/usr/local/bin/uv"
ansible_venv_bin: "{{ deploy_home }}/ansible_venv/bin"
ansible_python: "{{ ansible_venv_bin }}/python"
default_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
venv_bin: "{{ site_path }}/venv/bin"
python: "{{ venv_bin }}/python"
fqdn: "registry.staging.django-cast.com"
port: 10000
django_settings_module: "config.settings.production"
traefik_config_path: "/etc/traefik/dynamic/{{ username }}.traefik.yml"
systemd_unit_path: "/etc/systemd/system/{{ username }}.service"
deploy_base_url: "https://deploy.staging.wersdoerfer.de"
mailgun_domain: "mg.staging.django-cast.com"
gunicorn_number_of_workers: 3
